/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javapractice;

import com.mycompany.javapractice.SingletonClass;
import com.mycompany.javapractice.StudentModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class StudentTable extends javax.swing.JFrame {
    SingletonClass conn = SingletonClass.getInstance();
    
    ArrayList<StudentModel> studentList = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentTable.class.getName());

    /**
     * Creates new form StudentTable
     */
    public StudentTable() {
        initComponents();
        getStudent();
    }

    void getStudent(){


       String getData = "SELECT * FROM registerTable";
        
        String header[] = {"Id","Email","Password"};
        
        Statement state;
        try {
            state = conn.connection.createStatement();
            ResultSet result  = state.executeQuery(getData);
        
        DefaultTableModel model = new DefaultTableModel(null,header);
        StudentData.setModel(model);
        model.setRowCount(0);
        
        while(result.next()){
            studentList.add(new StudentModel(result.getInt("id"),result.getString("email"), result.getString("password")));
        
        }
        
        
        Object[] row = new Object[3];
        for(StudentModel item: studentList){
            row[0] = item.getId();
            row[1] = item.getEmail();
            row[2] = item.getPass();
            model.addRow(row);
        }
        } catch (SQLException ex) {
            System.getLogger(StudentTable.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        StudentData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentDataMouseClicked
        // TODO add your handling code here:
      

       int row = StudentData.getSelectedRow();
        Object value = StudentData.getValueAt(row, 0);
        int selectedId = Integer.parseInt(value.toString());
        
        System.out.println("Clicked");
       int choice =  JOptionPane.showConfirmDialog(this, "Update or Delete","Confirm Action", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            
         // Update
        }else{
           String deleteuser = "DELETE FROM registerTable WHERE ID=?";
           
           try{
               PreparedStatement ps = conn.connection.prepareCall(deleteuser);
               ps.setInt(1, selectedId);
               if(ps.executeUpdate() > 0){
                  
                JOptionPane.showMessageDialog(this, "Message Deleted");
                 getData();
               }
            
               
               
           }catch(SQLException exception){
            System.out.println("Delete Exception: "+exception);
        }
        }  
    }//GEN-LAST:event_StudentDataMouseClicked

    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new StudentTable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

}
